// Contrat entre le widget et la table Grist.
// Seuls Name, StartDate et EndDate sont obligatoires. Les autres champs peuvent
// rester non mappés et seront simplement masqués ou calculés par défaut.
export const GRIST_COLUMNS = [
  { name: 'Name', title: 'Nom du projet', type: 'Text', optional: false },
  { name: 'FullName', title: 'Nom complet du projet', type: 'Text', optional: true },
  { name: 'Wave', title: 'Vague', type: 'Text,Choice,Ref', optional: true },
  { name: 'StartDate', title: 'Date de début', type: 'Date,DateTime', optional: false },
  { name: 'EndDate', title: 'Date de fin initiale', type: 'Date,DateTime', optional: false },
  { name: 'Extended', title: 'Projet prolongé', type: 'Bool', optional: true },
  { name: 'ExtensionDate', title: 'Date de prolongation', type: 'Date,DateTime', optional: true },
  { name: 'Color', title: 'Couleur du projet', type: 'Text,Choice', optional: true, description: 'Format conseillé : #1F5FBF' },
  { name: 'Object', title: 'Objet du projet', type: 'Text', optional: true },
  { name: 'ScientificAxis', title: 'Axe scientifique', type: 'Text,Choice,Ref', optional: true },
  { name: 'Lead1', title: 'Porteur 1', type: 'Text,Ref', optional: true },
  { name: 'Lab1', title: 'Laboratoire du porteur 1', type: 'Text,Ref', optional: true },
  { name: 'Lead2', title: 'Porteur 2', type: 'Text,Ref', optional: true },
  { name: 'Lab2', title: 'Laboratoire du porteur 2', type: 'Text,Ref', optional: true },
  { name: 'Lead3', title: 'Porteur 3', type: 'Text,Ref', optional: true },
  { name: 'Lab3', title: 'Laboratoire du porteur 3', type: 'Text,Ref', optional: true },
  { name: 'TotalBudget', title: 'Budget total', type: 'Numeric,Int', optional: true },
  { name: 'DirectCosts', title: 'Coûts directs', type: 'Numeric,Int', optional: true },
  { name: 'Preciput', title: 'Préciput', type: 'Numeric,Int', optional: true },
  { name: 'Duration', title: 'Durée du projet', type: 'Numeric,Int,Text', optional: true },
  { name: 'HalfTime', title: 'Mi-temps', type: 'Date,DateTime,Text', optional: true },
  { name: 'Deliverable1', title: 'Livrable 1 — lancement', type: 'Text', optional: true },
  { name: 'Deliverable2', title: 'Livrable 2 — mi-temps', type: 'Text', optional: true },
  { name: 'Deliverable3', title: 'Livrable 3 — fin', type: 'Text', optional: true },
  { name: 'Milestone1Date', title: 'Date jalon lancement', type: 'Date,DateTime', optional: true },
  { name: 'Milestone2Date', title: 'Date jalon mi-temps', type: 'Date,DateTime', optional: true },
  { name: 'Milestone3Date', title: 'Date jalon final', type: 'Date,DateTime', optional: true },
  { name: 'Attachment', title: 'Document assigné', type: 'Attachments', optional: true }
];

export const EDITABLE_FIELDS = [
  { key: 'Name', label: 'Nom du projet', type: 'text', required: true },
  { key: 'FullName', label: 'Nom complet', type: 'text', className: 'is-wide' },
  { key: 'Wave', label: 'Vague', type: 'text' },
  { key: 'ScientificAxis', label: 'Axe scientifique', type: 'text' },
  { key: 'Color', label: 'Couleur', type: 'color' },
  { key: 'StartDate', label: 'Date de début', type: 'date' },
  { key: 'EndDate', label: 'Date de fin initiale', type: 'date' },
  { key: 'Extended', label: 'Projet prolongé', type: 'checkbox' },
  { key: 'ExtensionDate', label: 'Date de prolongation', type: 'date' },
  { key: 'Object', label: 'Objet du projet', type: 'textarea', className: 'is-full' },
  { key: 'Lead1', label: 'Porteur 1', type: 'text' },
  { key: 'Lab1', label: 'Laboratoire 1', type: 'text' },
  { key: 'Lead2', label: 'Porteur 2', type: 'text' },
  { key: 'Lab2', label: 'Laboratoire 2', type: 'text' },
  { key: 'Lead3', label: 'Porteur 3', type: 'text' },
  { key: 'Lab3', label: 'Laboratoire 3', type: 'text' },
  { key: 'TotalBudget', label: 'Budget total', type: 'number', step: '0.01' },
  { key: 'DirectCosts', label: 'Coûts directs', type: 'number', step: '0.01' },
  { key: 'Preciput', label: 'Préciput', type: 'number', step: '0.01' },
  { key: 'Deliverable1', label: 'Livrable lancement', type: 'text', className: 'is-wide' },
  { key: 'Milestone1Date', label: 'Date jalon lancement', type: 'date' },
  { key: 'Deliverable2', label: 'Livrable mi-temps', type: 'text', className: 'is-wide' },
  { key: 'Milestone2Date', label: 'Date jalon mi-temps', type: 'date' },
  { key: 'Deliverable3', label: 'Livrable final', type: 'text', className: 'is-wide' },
  { key: 'Milestone3Date', label: 'Date jalon final', type: 'date' }
];
